### ISSUE TITLE
Help user to find the correct orientation

### ISSUE THREAD

**Issue by ursfassler** [bilo/bilo-demo-app#1]
It is not clear if the physical Bilo base has the same orientation as the virtual one.

A solution may be tho show the colors of the physical LEDs also on the virtual one.

**Comment by ursfassler** [comment]
@huhme mentioned to turn the LEDs of the base entirely off during the game.

**Comment by huhme** [comment]
Adding colors on virtual base will validate the colors on physical base.

**Comment by huhme** [comment]
Base lighting request:

- Could we use the base LEDs to indicate powered on? Base lights could flash white momentarily then shut off.

-When the Bluetooth tooth connection is made could we have the base momentarily cycle of blue lighting indicating connection has been made.

**Comment by huhme** [comment]
Base lighting request:

Could we utilize just one led (the middle led) on each face of physical build base for the location ID, rather than the three we currently use?

Alternative solution could be to reduce brightness 50%  

The reason for the change is to tone down the visual element these led's currently produce. Its a bit overwhelming now.

**Comment by ursfassler** [comment]
At the moment, all 3 LEDs on one side are wired together. It is therefore not possible to only turn one on. Also the brightness can not be controlled by software for now.

Indicating power on with the base LEDs is helpful. Since it is a task for firmware I have not opened a new issue for that. 

I opened a new request for the connection indication: #11

**Comment by ursfassler** [comment]
Done with commit bbd7d3aca4ac53354d48af22a0919b2591b065ed

**Comment by bilo4ever** [comment]
testing my github account

latest update helps a lot with orientation - *thumbup*

**Comment by bilo4ever** [comment]
bilo4ever - stephan
