### ISSUE TITLE
Set one color for all block in Colorize

### ISSUE THREAD

**Issue by huhme** [bilo/bilo-demo-app#13]
Request to have block colors on LED test be user selected. All blocks would be color synchronized when the users chosen the desired color.

**Comment by ursfassler** [comment]
Who does it need for what? I see 2 different use cases:

1. As a worker I want to test if the LED are correctly mounted. I place the block on the base and check all 3 base colors. This is best done in the LED test game.
2. As a builder I want to set all blocks to the same color. I select a color via a button in the colorize game and all blocks get that color.

**Comment by huhme** [comment]
I was thinking this mod would be helpful to a builder. Specifically younger builders who struggle with the color selector wheel because they lack of finger dexterity and have difficulty in selecting vr blocks.

**Comment by ursfassler** [comment]
Am I correct with the following user story?

A user/builder opens the colorize game and places some physical blocks. There are some buttons on the screen that let you select a color. When one of the color buttons is pressed, all placed blocks get this color.
When the user places new blocks, they do NOT get the last selected color, they are black/unilluminated. The user can change the color of existing blocks with the color wheel.
When the user selects a new color for all blocks via the buttons on the screen, all placed blocks get the new color, even the ones that had another color before.

**Comment by huhme** [comment]
Yeah! That seems like a good method to edit block colors quickly.  ( I was thinking of a more basic solution, but your user store is better)

**Comment by ursfassler** [comment]
Done with commit cccd4d8bcb35085f1d2f3c21f9d8a18299622b21
