### ISSUE TITLE
Colorize Mode

### ISSUE THREAD

**Issue by bilo4ever** [bilo/bilo-demo-app#18]
function to select all blocks and color them in one go.

**Comment by ursfassler** [comment]
Is this the same user story as #13?
If so, can you explain there how you have an idea how to do that?
If it is something different, I need to know what you mean and why you need it.

**Comment by bilo4ever** [comment]
you are correct - my bad, I did not see that one.
how to?
i am spoiled by CAD software that gives me extensive range of tools for viewing and selecting. eventually we might get there. 
for now, your proposal of 'globally working' color buttons seem simple, yet effective.

**Comment by bilo4ever** [comment]
closed this as issue is being addressed as [#13](url)

**Comment by bilo4ever** [comment]
.....oh boy..... i need a crash course so i will behave appropriately here around in the future
