### ISSUE TITLE
virtual build base color

### ISSUE THREAD

**Issue by huhme** [bilo/bilo-demo-app#19]
Request to change the virtual build base from grey tones to whites. 
the shadows for the puzzle games can be chanced from white to bright pink or light blue see attached for reference.

the grey build base is just to drab... needs to be cheered up a touch. ^L^

![blue tree](https://cloud.githubusercontent.com/assets/25189004/26333565/1e9fc0fe-3f91-11e7-876d-810dd7e96e65.jpg)
![pink tree](https://cloud.githubusercontent.com/assets/25189004/26333566/1ea0f0fa-3f91-11e7-9e14-0ddbb77ba23c.jpg)

**Comment by ursfassler** [comment]
Yes, looks more friendly. The blocks should then be white too, I assume?

Changing the color is not difficult, finding the right colors is... best we do it when we meet.

**Comment by huhme** [comment]
Great! It's a date!

**Comment by ursfassler** [comment]
Done with commit d559f099c93656acbf3bdc84b6856ae8239d7389
